console.log(window.VueGWTExposedTypesRepository.com_axellience_vuegwtdemo_client_components_counter_CounterComponent);
console.log(window.VueGWTExposedTypesRepository.com_axellience_vuegwtdemo_client_components_todolist_TodoComponent);
console.log(window.VueGWTExposedTypesRepository.com_axellience_vuegwtdemo_client_components_todolist_TodoListComponent);